### ISSUE TITLE
About single image test

### ISSUE THREAD

**Issue by woduck** [LinjieLyu/DPI#3]
In your DPI paper, it is mentioned that it is possible to generate the envmap and pbrmaps with a single image input.
However, upon reviewing the actual code, I noticed that it selects 60 images randomly as input.

I would like to know if you have conducted any experiments with a single image input. If so, what were the results?

**Comment by LinjieLyu** [comment]
Hi @woduck. Sure, one could also use a single image as input and still get natural envmaps. We show the single input result in Fig. 1 and sec. 5.6 in our paper. However, the assumption is a well-initialized geometry is given, so the geometry is either reconstructed from multiview or 3D scan.
